{
  config,
  modulesPath,
  pkgs,
  lib,
  nixos-lima,
  ...
}:
let
  parseEnv =
    fileContent:
    let
      lines = builtins.split "\n" fileContent;
      nonEmptyLines = builtins.filter (
        line: builtins.isString (line) && line != "" && !(builtins.substring 0 1 line == "#")
      ) lines;
      parsed = builtins.listToAttrs (
        builtins.map (
          line:
          let
            parts = builtins.filter (line: builtins.isString line) (builtins.split "=" line);
            name = builtins.head parts;
            value = builtins.concatStringsSep "=" (builtins.tail parts);
          in
          {
            name = name;
            value = value;
          }
        ) nonEmptyLines
      );
    in
    parsed;

  # Read and parse the .env file injected by lima
  envFile = "/mnt/lima-cidata/lima.env";
  env = parseEnv (builtins.readFile envFile);
  user = env.LIMA_CIDATA_USER;
in
{
  #
  # This is a sample configuration module for a NixOS Lima VM
  #
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
    # The `lima` module sets up systemd services to support LimaVM
    # HACK(patrick.pichler): ENABLE AGAIN ONCE https://github.com/nixos-lima/nixos-lima/pull/52/changes HAS BEEN MERGED!!!

    # nixos-lima.nixosModules.lima

    ./custom-lima-init.nix
  ];

  # TODO: Consider setting some/all of the mandatory settings in `nixos-lima.nixosModules.lima`

  # Enable lima-init, lima-guestagent, other config needed for Lima support (via `nixos-lima.nixosModules.lima`)
  # HACK(patrick.pichler): ENABLE AGAIN ONCE https://github.com/nixos-lima/nixos-lima/pull/52/changes HAS BEEN MERGED!!!
  # services.lima.enable = false;

  # Using Flakes is highly-recommended, maybe even required.
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  virtualisation.docker.enable = true;

  # Grant user access to docker socket to use it without sudo
  users.extraGroups.docker.members = [ user ];

  # ssh
  services.openssh.enable = true;

  security = {
    sudo.wheelNeedsPassword = false;
  };

  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  boot.loader.grub = {
    device = "nodev";
    efiSupport = true;
    efiInstallAsRemovable = true;
  };
  fileSystems."/boot" = {
    device = lib.mkForce "/dev/vda1"; # /dev/disk/by-label/ESP
    fsType = "vfat";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    autoResize = true;
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "discard"
    ];
  };

  # misc
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # pkgs
  environment.systemPackages = with pkgs; [
    neovim
  ];

  # The usual warnings about changing `stateVersion` apply. Make sure to find and read them
  # before changing this value.
  system.stateVersion = "25.11";
}
