{
  modulesPath,
  pkgs,
  lib,
  ...
}:
let
  helpers = import ./helpers.nix { };
  user = helpers.env.LIMA_CIDATA_USER;
in
{
  #
  # This is a sample configuration module for a NixOS Lima VM
  #
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # Enable lima-init, lima-guestagent, other config needed for Lima support (via `nixos-lima.nixosModules.lima`)
  services.lima.enable = true;

  # Using Flakes is highly-recommended, maybe even required.
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  virtualisation.docker.enable = true;

  # Grant user access to docker socket to use it without sudo
  users.extraGroups.docker.members = [ user ];

  # ssh
  services.openssh.enable = true;

  security = {
    sudo.wheelNeedsPassword = false;
  };

  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  boot.loader.grub = {
    device = "nodev";
    efiSupport = true;
    efiInstallAsRemovable = true;
  };
  fileSystems."/boot" = {
    device = lib.mkForce "/dev/vda1"; # /dev/disk/by-label/ESP
    fsType = "vfat";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    autoResize = true;
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "discard"
    ];
  };

  # misc
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # pkgs
  environment.systemPackages = with pkgs; [
    neovim
    ghostty.terminfo
  ];

  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    # Add any missing dynamic libraries for unpackaged programs
    # here, NOT in environment.systemPackages
  ];

  # The usual warnings about changing `stateVersion` apply. Make sure to find and read them
  # before changing this value.
  system.stateVersion = "26.05";
}
